import placeholder from "../image/pexels-photo-794062.jpeg";
import placeholderLouge from "../image/pexels-photo-833052.jpeg";
import placeholderCasual from "../image/pexels-photo-3825145.jpeg";
import placeholderActive from "../image/pexels-photo-3687550.jpeg";
import placeholderEvening from "../image/pexels-photo-3825161.jpeg";

export const data = {
  products: [
    {
      id: 4,
      size: "L",
      description: "",
      image: placeholder,
      price: 950,
      category: "party",
      name: "Sequin Dress",
      quantity: "",
    },
    {
      id: 2,
      size: "S",
      description: "",
      image: placeholder,
      price: 540,
      category: "party",
      name: "Metallic Skirt",
      quantity: "",
    },
    {
      id: 1,
      size: "XS",
      description: "",
      image: placeholder,
      price: 850,
      category: "party",
      name: "Embellished Gown",
      quantity: "",
    },
    {
      id: 3,
      size: "M",
      description: "",
      image: placeholder,
      price: 380,
      category: "party",
      name: "Embriodered Top",
      quantity: "",
    },

    {
      id: 5,
      size: "XS",
      description: "",
      image: placeholderLouge,
      price: 550,
      category: "lounge",
      name: "Sweater",
      quantity: "",
    },
    {
      id: 6,
      size: "S",
      description: "",
      image: placeholderLouge,
      price: 180,
      category: "lounge",
      name: "Tie Dye Hoody",
      quantity: "",
    },
    {
      id: 7,
      size: "M",
      description: "",
      image: placeholderLouge,
      price: 650,
      category: "lounge",
      name: "Tropical Print Jumpsuit",
      quantity: "",
    },
    {
      id: 8,
      size: "L",
      description: "",
      image: placeholderLouge,
      price: 420,
      category: "lounge",
      name: "Knitted Pyjamas",
      quantity: "",
    },
    {
      id: 9,
      size: "XS",
      description: "",
      image: placeholderCasual,
      price: 720,
      category: "casual",
      name: "Denim Jacket",
      quantity: "",
    },
    {
      id: 10,
      size: "S",
      description: "",
      image: placeholderCasual,
      price: 550,
      category: "casual",
      name: "Polka Dot Top",
    },
    {
      id: 11,
      size: "M",
      description: "",
      image: placeholderCasual,
      price: 800,
      category: "casual",
      name: "Striped Shirt",
      quantity: "",
    },
    {
      id: 12,
      size: "L",
      description: "",
      image: placeholderCasual,
      price: 130,
      category: "casual",
      name: "Shirt Dress",
    },
    {
      id: 13,
      size: "XS",
      description: "",
      image: placeholderEvening,
      price: 900,
      category: "evening",
      name: "Little Black Dress",
      quantity: "",
    },
    {
      id: 14,
      size: "S",
      description: "",
      image: placeholderEvening,
      price: 490,
      category: "evening",
      name: "Cross Back Red Dress",
      quantity: "",
    },
    {
      id: 15,
      size: "M",
      description: "",
      image: placeholderEvening,
      price: 380,
      category: "evening",
      name: "Pleated Maxi Skirt",
      quantity: "",
    },
    {
      id: 16,
      size: "L",
      description: "",
      image: placeholderEvening,
      price: 570,
      category: "evening",
      name: "Animal Print Mini Skirt",
      quantity: "",
    },
    {
      id: 17,
      size: "XS",
      description: "",
      image: placeholderActive,
      price: 750,
      category: "active",
      name: "Colour Block Sweatshirt",
      quantity: "",
    },
    {
      id: 18,
      size: "S",
      description: "",
      image: placeholderActive,
      price: 500,
      category: "active",
      name: "Camo Shorts",
      quantity: "",
    },
    {
      id: 19,
      size: "M",
      description: "",
      image: placeholderActive,
      price: 400,
      category: "active",
      name: "Distressed Tshirt",
      quantity: "",
    },
    {
      id: 20,
      size: "L",
      description: "",
      image: placeholderActive,
      price: 540,
      category: "active",
      name: "Seamless Sports Bra",
      quantity: "",
    },
  ],
};
