import placeholder from "../image/pexels-photo-794062.jpeg";

export const data = {
  products: [
    {
        id: 4,
        size: "L",
        description: "",
        image: placeholder,
        price: "4€",
        category: "party",
      },
    {
      id: 2,
      size: "S",
      description: "",
      image: placeholder,
      price: "2€",
      category: "party",
    },
    {
        id: 1,
        size: "XS",
        description: "",
        image: placeholder,
        price: "1€",
        category: "party",
      },{
      id: 3,
      size: "M",
      description: "",
      image: placeholder,
      price: "3€",
      category: "party",
    },
    
    {
      id: 5,
      size: "XS",
      description: "",
      image: placeholder,
      price: "5€",
      category: "lounge",
    },
    {
      id: 6,
      size: "S",
      description: "",
      image: placeholder,
      price: "100€",
      category: "lounge",
    },
    {
      id: 7,
      size: "M",
      description: "",
      image: placeholder,
      price: "100€",
      category: "lounge",
    },
    {
      id: 8,
      size: "L",
      description: "",
      image: placeholder,
      price: "100€",
      category: "lounge",
    },
    {
      id: 9,
      size: "XS",
      description: "",
      image: placeholder,
      price: "100€",
      category: "casual",
    },
    {
      id: 10,
      size: "S",
      description: "",
      image: placeholder,
      price: "100€",
      category: "casual",
    },
    {
      id: 11,
      size: "M",
      description: "",
      image: placeholder,
      price: "100€",
      category: "casual",
    },
    {
      id: 12,
      size: "L",
      description: "",
      image: placeholder,
      price: "100€",
      category: "casual",
    },
    {
      id: 13,
      size: "XS",
      description: "",
      image: placeholder,
      price: "100€",
      category: "evening",
    },
    {
      id: 14,
      size: "S",
      description: "",
      image: placeholder,
      price: "100€",
      category: "evening",
    },
    {
      id: 15,
      size: "M",
      description: "",
      image: placeholder,
      price: "100€",
      category: "evening",
    },
    {
      id: 16,
      size: "L",
      description: "",
      image: placeholder,
      price: "100€",
      category: "evening",
    },
    {
      id: 17,
      size: "XS",
      description: "",
      image: placeholder,
      price: "100€",
      category: "active",
    },
    {
      id: 18,
      size: "S",
      description: "",
      image: placeholder,
      price: "100€",
      category: "active",
    },
    {
      id: 19,
      size: "M",
      description: "",
      image: placeholder,
      price: "100€",
      category: "active",
    },
    {
      id: 20,
      size: "L",
      description: "",
      image: placeholder,
      price: "100€",
      category: "active",
    },
  ],
};
